#!/groovy

node {
    def work_dir = '$JENKINS_HOME/project'

    stage('Git Checkout') {
        checkout (
            [
            $class: 'GitSCM',
            userRemoteConfigs: [[url: "${CJK_GIT_URL}",credentialsId: "${CREDENTIALS_ID}" ]],
            branches: [[name: "${BRANCH_NAME}"]]
            ]
        )

    }
    stage('Install Ansible') {
        sh ('''
            sudo amazon-linux-extras install ansible2
            ansible --version
            if [ ! -d $JENKINS_HOME/project ];
            then
                echo $PWD
                mkdir -p $JENKINS_HOME/project
            else 
                echo 'Failed Setup'
            fi
        ''')
    }
    stage('Execute Playbook') {
        dir(work_dir){
            sh('''
                ansiblePlaybook(
                    playbook: 'ansible/site.yml',
                    become: 'true'
                    credentialsId: 'Ansible_cred'
                    inventory: 'ansible/hosts-dev'
                )

            ''')
        }
    }
}
